"""
AI Agency — FastAPI Workflow Executor
-------------------------------------
Runs workflows generated by the fine-tuned Mistral model.
Supports: gmail.read_email, gmail.send_email, gmail.search_emails,
          sheets.read_rows, sheets.append_row, sheets.update_cell,
          condition (if/then/else branching)

Usage:
    pip install fastapi uvicorn google-auth google-auth-oauthlib
                google-auth-httplib2 google-api-python-client
                mistralai python-dotenv weave
    python3 main.py

Endpoints:
    POST /conversation        — send a message to Aria (the AI agent)
    POST /workflow/generate   — turn a transcript into a workflow JSON
    POST /workflow/run        — execute a workflow JSON for real
    GET  /workflow/{id}       — get workflow status
    GET  /auth/google         — trigger Google OAuth flow
"""

import os
import json
import re
import uuid
import base64
import weave
from datetime import datetime
from typing import Any
from email.mime.text import MIMEText

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

from mistralai import Mistral

# ── Load .env ──────────────────────────────────────────────────────────────────

try:
    from dotenv import load_dotenv
    current = os.path.abspath(__file__)
    for _ in range(4):
        current = os.path.dirname(current)
        env_path = os.path.join(current, ".env")
        if os.path.exists(env_path):
            load_dotenv(env_path)
            break
except ImportError:
    pass

MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY")
if not MISTRAL_API_KEY:
    raise EnvironmentError("❌ MISTRAL_API_KEY not found in .env")

# ── W&B Weave (tracks every live AI call for your demo dashboard) ──────────────

weave.init("ai-agency-app")

# ── Config ─────────────────────────────────────────────────────────────────────

# After fine-tuning completes, this file will contain your model ID.
# Until then, we fall back to mistral-large-latest so you can test immediately.
MODEL_ID_FILE     = "fine_tuned_model_id.txt"
FALLBACK_MODEL    = "mistral-large-latest"
CREDENTIALS_FILE  = "credentials.json"
TOKEN_FILE        = "token.json"

# Google API scopes needed
SCOPES = [
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/spreadsheets",
]

def get_active_model() -> str:
    """Use fine-tuned model if available, otherwise fall back to Large."""
    if os.path.exists(MODEL_ID_FILE):
        with open(MODEL_ID_FILE) as f:
            model_id = f.read().strip()
        if model_id:
            return model_id
    return FALLBACK_MODEL

# ── Google Auth ────────────────────────────────────────────────────────────────

def get_google_credentials() -> Credentials:
    """
    Handles Google OAuth. On first run, opens a browser window for login.
    After that, reuses the saved token.json automatically.
    """
    creds = None

    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CREDENTIALS_FILE):
                raise FileNotFoundError(
                    f"❌ {CREDENTIALS_FILE} not found. "
                    "Download it from Google Cloud Console first."
                )
            flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)

        with open(TOKEN_FILE, "w") as token:
            token.write(creds.to_json())

    return creds

def get_gmail_service():
    return build("gmail", "v1", credentials=get_google_credentials())

def get_sheets_service():
    return build("sheets", "v4", credentials=get_google_credentials())

# ── Template Variable Resolver ─────────────────────────────────────────────────

def resolve(value: Any, context: dict) -> Any:
    """
    Replaces {{variable}} placeholders with real values from context.
    Works on strings, lists, and dicts recursively.

    Example:
        resolve("Hello {{email_data.sender}}", {"email_data": {"sender": "bob@co.com"}})
        → "Hello bob@co.com"
    """
    if isinstance(value, str):
        def replacer(match):
            path = match.group(1).strip()
            parts = path.split(".")
            current = context
            for part in parts:
                if isinstance(current, dict):
                    current = current.get(part, match.group(0))
                else:
                    return match.group(0)
            return str(current)
        return re.sub(r"\{\{(.+?)\}\}", replacer, value)
    elif isinstance(value, list):
        return [resolve(item, context) for item in value]
    elif isinstance(value, dict):
        return {k: resolve(v, context) for k, v in value.items()}
    return value

# ── Action Executors ───────────────────────────────────────────────────────────

def execute_gmail_read_email(config: dict, context: dict) -> dict:
    """Reads the most recent matching email from Gmail."""
    service = get_gmail_service()

    # Build query from trigger context if available
    query = context.get("_trigger_query", "is:unread")
    results = service.users().messages().list(
        userId="me", q=query, maxResults=1
    ).execute()

    messages = results.get("messages", [])
    if not messages:
        return {"error": "No matching emails found"}

    msg = service.users().messages().get(
        userId="me", id=messages[0]["id"], format="full"
    ).execute()

    headers = {h["name"]: h["value"] for h in msg["payload"]["headers"]}
    extract_fields = config.get("extract_fields", ["sender", "subject", "body", "date"])

    # Extract plain text body
    body = ""
    if "parts" in msg["payload"]:
        for part in msg["payload"]["parts"]:
            if part["mimeType"] == "text/plain":
                body = base64.urlsafe_b64decode(
                    part["body"]["data"].encode("ASCII")
                ).decode("utf-8")
                break
    elif "body" in msg["payload"] and "data" in msg["payload"]["body"]:
        body = base64.urlsafe_b64decode(
            msg["payload"]["body"]["data"].encode("ASCII")
        ).decode("utf-8")

    result = {}
    field_map = {
        "sender":  headers.get("From", ""),
        "subject": headers.get("Subject", ""),
        "date":    headers.get("Date", ""),
        "body":    body,
        "message_id": messages[0]["id"],
    }
    for field in extract_fields:
        if field in field_map:
            result[field] = field_map[field]

    return result


def execute_gmail_send_email(config: dict, context: dict) -> dict:
    """Sends an email via Gmail."""
    service = get_gmail_service()

    to      = resolve(config.get("to", ""), context)
    subject = resolve(config.get("subject", ""), context)
    body    = resolve(config.get("body", ""), context)

    message = MIMEText(body)
    message["to"]      = to
    message["subject"] = subject

    raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
    service.users().messages().send(
        userId="me", body={"raw": raw}
    ).execute()

    return {"sent": True, "to": to, "subject": subject}


def execute_gmail_search_emails(config: dict, context: dict) -> dict:
    """Searches Gmail and returns matching email summaries."""
    service = get_gmail_service()

    query       = resolve(config.get("query", ""), context)
    max_results = config.get("max_results", 10)

    results = service.users().messages().list(
        userId="me", q=query, maxResults=max_results
    ).execute()

    messages = results.get("messages", [])
    emails = []
    for msg_ref in messages:
        msg = service.users().messages().get(
            userId="me", id=msg_ref["id"], format="metadata",
            metadataHeaders=["From", "Subject", "Date"]
        ).execute()
        headers = {h["name"]: h["value"] for h in msg["payload"]["headers"]}
        emails.append({
            "id":      msg_ref["id"],
            "sender":  headers.get("From", ""),
            "subject": headers.get("Subject", ""),
            "date":    headers.get("Date", ""),
        })

    return {"emails": emails, "count": len(emails)}


def execute_sheets_read_rows(config: dict, context: dict) -> dict:
    """Reads rows from a Google Sheet."""
    service = get_sheets_service()

    spreadsheet_id = resolve(config.get("spreadsheet_id", ""), context)
    sheet_name     = resolve(config.get("sheet_name", "Sheet1"), context)
    range_notation = resolve(config.get("range", "A:Z"), context)
    full_range     = f"{sheet_name}!{range_notation}"

    result = service.spreadsheets().values().get(
        spreadsheetId=spreadsheet_id, range=full_range
    ).execute()

    rows = result.get("values", [])
    return {"rows": rows, "count": len(rows)}


def execute_sheets_append_row(config: dict, context: dict) -> dict:
    """Appends a new row to a Google Sheet."""
    service = get_sheets_service()

    spreadsheet_id = resolve(config.get("spreadsheet_id", ""), context)
    sheet_name     = resolve(config.get("sheet_name", "Sheet1"), context)
    row_data       = resolve(config.get("row_data", []), context)

    service.spreadsheets().values().append(
        spreadsheetId=spreadsheet_id,
        range=f"{sheet_name}!A1",
        valueInputOption="USER_ENTERED",
        body={"values": [row_data]},
    ).execute()

    return {"appended": True, "row": row_data}


def execute_sheets_update_cell(config: dict, context: dict) -> dict:
    """Updates a single cell in a Google Sheet."""
    service = get_sheets_service()

    spreadsheet_id = resolve(config.get("spreadsheet_id", ""), context)
    sheet_name     = resolve(config.get("sheet_name", "Sheet1"), context)
    cell           = resolve(config.get("cell", "A1"), context)
    value          = resolve(config.get("value", ""), context)
    full_range     = f"{sheet_name}!{cell}"

    service.spreadsheets().values().update(
        spreadsheetId=spreadsheet_id,
        range=full_range,
        valueInputOption="USER_ENTERED",
        body={"values": [[value]]},
    ).execute()

    return {"updated": True, "cell": cell, "value": value}


def execute_condition(config: dict, context: dict) -> str:
    """
    Evaluates an if/then/else condition and returns the next step ID.

    Supports simple operators: contains, equals, not_equals, gt, lt
    Example config:
        { "if": "{{email_data.sender}} contains supplier.com",
          "then": "step_3", "else": "step_5" }
    """
    condition_str = resolve(config.get("if", ""), context)
    then_step     = config.get("then")
    else_step     = config.get("else")

    # Parse "VALUE operator OPERAND"
    patterns = [
        (r"(.+?)\s+contains\s+(.+)",     lambda a, b: b.lower() in a.lower()),
        (r"(.+?)\s+equals\s+(.+)",       lambda a, b: a.strip() == b.strip()),
        (r"(.+?)\s+not_equals\s+(.+)",   lambda a, b: a.strip() != b.strip()),
        (r"(.+?)\s+>\s+(.+)",            lambda a, b: float(a) > float(b)),
        (r"(.+?)\s+<\s+(.+)",            lambda a, b: float(a) < float(b)),
    ]

    result = False
    for pattern, evaluator in patterns:
        match = re.match(pattern, condition_str.strip())
        if match:
            try:
                result = evaluator(match.group(1).strip(), match.group(2).strip())
            except Exception:
                result = False
            break

    return then_step if result else else_step

# ── Workflow Runner ────────────────────────────────────────────────────────────

ACTION_MAP = {
    "gmail.read_email":    execute_gmail_read_email,
    "gmail.send_email":    execute_gmail_send_email,
    "gmail.search_emails": execute_gmail_search_emails,
    "sheets.read_rows":    execute_sheets_read_rows,
    "sheets.append_row":   execute_sheets_append_row,
    "sheets.update_cell":  execute_sheets_update_cell,
}

def run_workflow(workflow: dict, user_context: dict = {}) -> dict:
    """
    Executes a workflow JSON step by step.
    Returns a full execution log with results from each step.
    """
    steps      = {s["id"]: s for s in workflow.get("steps", [])}
    context    = {
        "workflow": {"run_timestamp": datetime.utcnow().isoformat()},
        "user":     user_context,
        **user_context,
    }
    execution_log = []
    current_step_id = workflow["steps"][0]["id"] if workflow["steps"] else None

    while current_step_id and current_step_id in steps:
        step   = steps[current_step_id]
        action = step["action"]
        config = step.get("config", {})
        log_entry = {
            "step_id": current_step_id,
            "name":    step.get("name", ""),
            "action":  action,
            "status":  "running",
        }

        try:
            if action == "condition":
                next_step = execute_condition(config, context)
                log_entry["result"] = {"branched_to": next_step}
                log_entry["status"] = "completed"
                execution_log.append(log_entry)
                current_step_id = next_step
                continue
            elif action in ACTION_MAP:
                result = ACTION_MAP[action](config, context)
                # Store output in context so later steps can reference it
                output_var = step.get("output_variable")
                if output_var:
                    context[output_var] = result
                log_entry["result"] = result
                log_entry["status"] = "completed"
            else:
                log_entry["status"] = "skipped"
                log_entry["result"] = {"reason": f"Unknown action: {action}"}

        except Exception as e:
            log_entry["status"] = "failed"
            log_entry["error"]  = str(e)
            execution_log.append(log_entry)
            break  # stop execution on failure

        execution_log.append(log_entry)

        # Move to next step sequentially (unless condition already jumped)
        step_ids = list(steps.keys())
        current_idx = step_ids.index(current_step_id)
        current_step_id = (
            step_ids[current_idx + 1] if current_idx + 1 < len(step_ids) else None
        )

    return {
        "workflow_id":    workflow.get("workflow_id"),
        "workflow_name":  workflow.get("name"),
        "status":         "completed" if all(e["status"] == "completed" for e in execution_log) else "failed",
        "steps_executed": len(execution_log),
        "execution_log":  execution_log,
        "completed_at":   datetime.utcnow().isoformat(),
    }

# ── Mistral AI Agent (the conversation + workflow generation) ──────────────────

ARIA_SYSTEM_PROMPT = """You are Aria, a warm and friendly AI assistant helping non-technical 
office workers automate their repetitive tasks. 

Your job is to have a natural conversation to understand what the user wants to automate, 
then generate a workflow JSON.

CONVERSATION RULES:
- Ask 3-5 targeted follow-up questions before generating anything
- Use simple everyday language — never say "trigger", "node", "webhook", "API"
- Be warm, encouraging and human — like a smart colleague, not a form
- When you have enough info, say "Great, I have everything I need! Let me build that for you..."
- Then output the workflow JSON wrapped in <workflow></workflow> tags

WORKFLOW JSON SCHEMA:
{
  "workflow_id": "wf_<random 8 chars>",
  "name": "<short name>",
  "description": "<one sentence>",
  "created_from_transcript": true,
  "trigger": {
    "type": "email_received | manual",
    "config": { "from_filter": "...", "subject_filter": "...", "match": "contains|exact" }
  },
  "steps": [
    {
      "id": "step_1",
      "name": "<human name>",
      "action": "<one of 7 actions>",
      "config": { ... },
      "output_variable": "<name>"
    }
  ],
  "meta": { "estimated_time_saved_minutes": 0, "runs": 0, "last_run": null, "status": "active" }
}

ALLOWED ACTIONS (only these 7):
gmail.read_email, gmail.send_email, gmail.search_emails,
sheets.read_rows, sheets.append_row, sheets.update_cell, condition
"""

mistral_client = Mistral(api_key=MISTRAL_API_KEY)

@weave.op()
def call_aria(messages: list) -> str:
    """Calls the AI agent and returns its response. Tracked by W&B Weave."""
    model = get_active_model()
    response = mistral_client.chat.complete(
        model=model,
        messages=messages,
        temperature=0.7,
        max_tokens=1500,
    )
    return response.choices[0].message.content

def extract_workflow_from_response(text: str) -> dict | None:
    """Pulls workflow JSON out of <workflow>...</workflow> tags if present."""
    match = re.search(r"<workflow>(.*?)</workflow>", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1).strip())
        except json.JSONDecodeError:
            return None
    return None

# ── FastAPI App ────────────────────────────────────────────────────────────────

app = FastAPI(title="AI Agency", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this in production
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory stores (fine for hackathon)
conversations: dict[str, list] = {}
workflows:     dict[str, dict] = {}

# ── Request/Response Models ────────────────────────────────────────────────────

class MessageRequest(BaseModel):
    conversation_id: str | None = None
    message: str

class WorkflowRunRequest(BaseModel):
    workflow: dict
    user_context: dict = {}   # spreadsheet_id, email etc. from frontend

# ── Endpoints ──────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "status": "running",
        "model":  get_active_model(),
        "weave":  "active",
    }


@app.get("/auth/google")
def auth_google():
    """
    Call this endpoint once to trigger the Google OAuth browser flow.
    After login it saves token.json so all future calls work automatically.
    """
    try:
        get_google_credentials()
        return {"status": "authenticated", "token_saved": TOKEN_FILE}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/conversation")
def conversation(req: MessageRequest):
    """
    Main conversation endpoint. Send Natalie's messages here.
    Returns Aria's response + the workflow JSON if it's ready.
    
    Frontend flow:
        1. User types/speaks → POST /conversation
        2. Aria responds with follow-up question
        3. Repeat until Aria says she's ready
        4. Response includes workflow JSON → show visualizer
    """
    # Get or create conversation history
    conv_id = req.conversation_id or str(uuid.uuid4())
    if conv_id not in conversations:
        conversations[conv_id] = [
            {"role": "system", "content": ARIA_SYSTEM_PROMPT}
        ]

    conversations[conv_id].append({"role": "user", "content": req.message})

    # Call Aria
    aria_response = call_aria(conversations[conv_id])
    conversations[conv_id].append({"role": "assistant", "content": aria_response})

    # Check if a workflow was generated
    workflow = extract_workflow_from_response(aria_response)
    clean_response = re.sub(r"<workflow>.*?</workflow>", "", aria_response, flags=re.DOTALL).strip()

    if workflow:
        wf_id = workflow.get("workflow_id", str(uuid.uuid4()))
        workflows[wf_id] = workflow

    return {
        "conversation_id": conv_id,
        "response":        clean_response,
        "workflow_ready":  workflow is not None,
        "workflow":        workflow,
    }


@app.post("/workflow/run")
def run_workflow_endpoint(req: WorkflowRunRequest):
    """
    Executes a workflow for real using Gmail + Sheets APIs.
    Pass the workflow JSON + any user-specific context (spreadsheet IDs etc.)
    """
    try:
        result = run_workflow(req.workflow, req.user_context)
        # Store result
        wf_id = req.workflow.get("workflow_id", "unknown")
        if wf_id in workflows:
            workflows[wf_id]["meta"]["runs"] += 1
            workflows[wf_id]["meta"]["last_run"] = datetime.utcnow().isoformat()
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/workflow/{workflow_id}")
def get_workflow(workflow_id: str):
    """Returns a stored workflow and its metadata."""
    if workflow_id not in workflows:
        raise HTTPException(status_code=404, detail="Workflow not found")
    return workflows[workflow_id]


@app.get("/health")
def health():
    return {
        "status":       "healthy",
        "model":        get_active_model(),
        "google_auth":  os.path.exists(TOKEN_FILE),
        "timestamp":    datetime.utcnow().isoformat(),
    }


# ── Run ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    print(f"\n🚀 AI Agency API starting...")
    print(f"   Model: {get_active_model()}")
    print(f"   Docs:  http://localhost:8000/docs\n")
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
