"""
Fine-Tuning Job — AI Agency
============================
1. Uploads training_data.jsonl + eval_data.jsonl to Mistral
2. Kicks off fine-tuning on ministral-8b-latest
3. Polls for progress and streams metrics to W&B in real time
4. Saves the final model ID so your app can use it

After it finishes, your fine-tuned model ID is saved to:
    fine_tuned_model_id.txt
"""

import os
import time
import json
import wandb
from mistralai import Mistral

# ── Load .env ─────────────────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    current = os.path.abspath(__file__)
    for _ in range(4):
        current = os.path.dirname(current)
        env_path = os.path.join(current, ".env")
        if os.path.exists(env_path):
            load_dotenv(env_path)
            print(f"✅ Loaded .env from {env_path}")
            break
except ImportError:
    pass

MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY")
WANDB_API_KEY   = os.environ.get("WANDB_API_KEY")

if not MISTRAL_API_KEY:
    raise EnvironmentError("❌ MISTRAL_API_KEY not found. Check your .env file.")
if not WANDB_API_KEY:
    raise EnvironmentError("❌ WANDB_API_KEY not found. Check your .env file.")

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_TO_FINETUNE = "ministral-8b-latest"   # the model we're training
TRAIN_FILE        = "training_data.jsonl"   # generated by generate_training_data.py
EVAL_FILE         = "eval_data.jsonl"
OUTPUT_ID_FILE    = "fine_tuned_model_id.txt"
POLL_INTERVAL_SEC = 30                      # how often to check job status

# Hyperparameters — these are safe defaults for a hackathon
# training_steps: how many batches to train on. 100-200 is enough for ~100 examples
# learning_rate:  how fast the model updates. 1e-4 is standard for fine-tuning
HYPERPARAMETERS = {
    "training_steps": 100,
    "learning_rate": 1e-4,
}

# ── Init ───────────────────────────────────────────────────────────────────────

client = Mistral(api_key=MISTRAL_API_KEY)

wandb.init(
    project="ai-agency-finetune",
    name=f"finetune-{MODEL_TO_FINETUNE}",
    config={
        "base_model":     MODEL_TO_FINETUNE,
        "train_file":     TRAIN_FILE,
        "eval_file":      EVAL_FILE,
        **HYPERPARAMETERS,
    }
)

# ── Step 1: Upload files ───────────────────────────────────────────────────────

print("\n📤 Uploading training files to Mistral...")

def upload_file(path: str, purpose: str = "fine-tune") -> str:
    """Upload a JSONL file and return its file ID."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"❌ {path} not found.\n"
            f"   Make sure generate_training_data.py has finished running first."
        )
    
    with open(path, "rb") as f:
        response = client.files.upload(
            file={"file_name": os.path.basename(path), "content": f},
            purpose=purpose,
        )
    print(f"   ✅ {path} → file ID: {response.id}")
    return response.id

train_file_id = upload_file(TRAIN_FILE)
eval_file_id  = upload_file(EVAL_FILE)

wandb.log({
    "train_file_id": train_file_id,
    "eval_file_id":  eval_file_id,
})

# ── Step 2: Create fine-tuning job ────────────────────────────────────────────

print(f"\n🚀 Creating fine-tuning job on {MODEL_TO_FINETUNE}...")

job = client.fine_tuning.jobs.create(
    model=MODEL_TO_FINETUNE,
    training_files=[{"file_id": train_file_id, "weight": 1}],
    validation_files=[eval_file_id],
    hyperparameters=HYPERPARAMETERS,
    auto_start=True,    # start immediately without manual confirmation
    suffix="ai-agency", # your model will be named ft:ministral-8b:ai-agency:xxxxx
)

print(f"   ✅ Job created: {job.id}")
print(f"   Status: {job.status}")
print(f"\n⏳ Training has started. This takes ~20-60 minutes.")
print(f"   Watch live at: https://wandb.ai/klaraa-konkel-mistral-ai/ai-agency-finetune\n")

wandb.log({"job_id": job.id, "initial_status": job.status})

# ── Step 3: Poll for progress ─────────────────────────────────────────────────
# Mistral's API doesn't stream training metrics directly,
# but we can poll the job status and log checkpoints as they appear.

STATUS_EMOJI = {
    "QUEUED":     "⏳",
    "STARTED":    "🔄",
    "RUNNING":    "🔄",
    "SUCCEEDED":  "✅",
    "FAILED":     "❌",
    "CANCELLED":  "🚫",
}

last_checkpoint_count = 0

while True:
    job = client.fine_tuning.jobs.get(job_id=job.id)
    status  = job.status
    emoji   = STATUS_EMOJI.get(status, "❓")
    elapsed = int(time.time())

    print(f"   {emoji} Status: {status}")

    # Log any new checkpoints (these contain train/eval loss)
    if hasattr(job, "checkpoints") and job.checkpoints:
        new_checkpoints = job.checkpoints[last_checkpoint_count:]
        for checkpoint in new_checkpoints:
            metrics = {
                "step":       checkpoint.step_number,
            }
            # Log train loss if available
            if hasattr(checkpoint, "metrics") and checkpoint.metrics:
                m = checkpoint.metrics
                if hasattr(m, "train_loss") and m.train_loss is not None:
                    metrics["train_loss"] = m.train_loss
                    print(f"      train_loss: {m.train_loss:.4f}")
                if hasattr(m, "valid_loss") and m.valid_loss is not None:
                    metrics["eval_loss"] = m.valid_loss
                    print(f"      eval_loss:  {m.valid_loss:.4f}")
                if hasattr(m, "valid_mean_token_accuracy") and m.valid_mean_token_accuracy is not None:
                    metrics["eval_token_accuracy"] = m.valid_mean_token_accuracy
                    print(f"      eval_accuracy: {m.valid_mean_token_accuracy:.4f}")
            wandb.log(metrics)
        last_checkpoint_count = len(job.checkpoints)

    # Terminal states — stop polling
    if status in ("SUCCEEDED", "FAILED", "CANCELLED"):
        break

    time.sleep(POLL_INTERVAL_SEC)

# ── Step 4: Handle result ──────────────────────────────────────────────────────

if job.status == "SUCCEEDED":
    model_id = job.fine_tuned_model

    print(f"\n🎉 Fine-tuning complete!")
    print(f"   Your model ID: {model_id}")

    # Save model ID to a file so your FastAPI app can read it
    with open(OUTPUT_ID_FILE, "w") as f:
        f.write(model_id)
    print(f"   Saved to: {OUTPUT_ID_FILE}")

    # Log final model info to W&B
    wandb.summary["fine_tuned_model_id"] = model_id
    wandb.summary["status"]              = "SUCCEEDED"

    # Save as W&B artifact for traceability
    artifact = wandb.Artifact("fine-tuned-model", type="model")
    artifact.add_file(OUTPUT_ID_FILE)
    wandb.log_artifact(artifact)

    print(f"\n📊 Full training run logged at:")
    print(f"   https://wandb.ai/klaraa-konkel-mistral-ai/ai-agency-finetune")
    print(f"\n✨ Next step: update your app to use model ID: {model_id}")

elif job.status == "FAILED":
    error = getattr(job, "error", "Unknown error")
    print(f"\n❌ Fine-tuning failed: {error}")
    wandb.summary["status"] = "FAILED"
    wandb.summary["error"]  = str(error)

wandb.finish()
